# Generated by Django 5.1.1 on 2024-09-30 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasklists', '0002_tasklist_author_usertasklistpermissions'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserTaskListPermissions',
        ),
    ]
